format = '$directory$git_branch$git_state$git_metrics$git_status$cmd_duration $character'

[cmd_duration]
format = '\[[⏱ $duration]($style)\]'

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
